
FROM python:3.9-slim-buster
RUN apt-get update
RUN apt-get install git -y
RUN apt-get install tk -y
RUN apt-get install gcc -y
RUN apt-get install wget -y
RUN apt-get install libsndfile1 -y 
RUN apt-get install libportaudio2 -y
RUN apt-get install ffmpeg -y

RUN pip install --upgrade pip

WORKDIR /code/

RUN git clone https://github.com/svartalf/python-opus
RUN git clone https://github.com/kozzion/breaker_core
RUN git clone https://github.com/kozzion/breaker_aws
RUN git clone https://github.com/kozzion/breaker_discord

WORKDIR /code/python-opus
RUN pip3 install -e .

WORKDIR /code/breaker_core
RUN git pull
RUN pip3 install -e .

WORKDIR /code/breaker_aws
RUN git pull
RUN pip3 install -e .

RUN ls
WORKDIR /code/breaker_discord
RUN git pull
RUN pip3 install -e .

# copy config
WORKDIR /code/breaker_discord/script
# TODO mount this instead
COPY config.cfg config.cfg 
CMD [ "python3", "breaker_discord.py"]
