
FROM python:3.9-slim-buster
RUN apt-get update
RUN apt-get install git -y
RUN apt-get install tk -y
RUN apt-get install gcc -y
RUN apt-get install wget -y
RUN apt-get install libsndfile1 -y 
RUN apt-get install libportaudio2 -y
RUN apt-get install ffmpeg -y

RUN pip install --upgrade pip

WORKDIR /code/

RUN git clone https://github.com/svartalf/python-opus
RUN git clone https://github.com/kozzion/breaker_core
RUN git clone https://github.com/kozzion/breaker_aws

RUN pip3 install -e /code/python-opus
RUN pip3 install -e /code/breaker_core
RUN pip3 install -e /code/breaker_aws

# always get latest version
ADD "https://www.random.org/cgi-bin/randbyte?nbytes=10&format=h" skipcache
RUN git clone https://github.com/kozzion/breaker_discord
RUN pip3 install -e /code/breaker_discord

# copy config
WORKDIR /code/breaker_discord/script

CMD [ "python3", "run_bot.py"]
