
FROM python:3.9-slim-buster
RUN apt-get update
RUN apt-get install git -y
RUN apt-get install tk -y
RUN apt-get install gcc -y
RUN apt-get install wget -y
RUN apt-get install libsndfile1 -y 
RUN apt-get install libportaudio2 -y

RUN pip install --upgrade pip
WORKDIR /breaker/
RUN git clone https://github.com/kozzion/breaker_core
RUN git clone https://github.com/kozzion/breaker_aws
RUN git clone https://github.com/kozzion/breaker_discord

WORKDIR /breaker/breaker_core
RUN git pull
RUN pip3 install -e .

WORKDIR /breaker/breaker_aws
RUN git pull
RUN pip3 install -e .

RUN apt-get install ffmpeg -y
RUN ls
WORKDIR /breaker/breaker_discord
RUN git pull
RUN pip3 install -e .


#

# copy config
WORKDIR /breaker/breaker_discord/test
COPY config.cfg config.cfg
CMD [ "python3", "bot_clone.py"]